src/lv2gui.cpp
src/makerdf.cpp

The analyzer plugin is useless without graphs,
which right now depend on LV2 instance+data-access.
Also the instance/data-access feature was wrongly placed as plugin property,
when in fact it's a UI property.

Make Analyzer UI require instance-access

---

gui/Makefile.am
src/calf/Makefile.am

Some files were missing from the tarball created by make dist in the git repo.
I don't know if all the files added are required, but at least now I can compile the tarball.

make dist: add some missing files

---

src/lv2wrap.cpp

compiling without LV2 shows the following error:
```
clang: warning: optimization flag '-finline-limit=80' is not supported
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: optimization flag '-finline-functions-called-once' is not supported
clang: warning: argument unused during compilation: '-finline-limit=80'
clang: warning: argument unused during compilation: '-finline-functions'
clang: warning: argument unused during compilation: '-finline-functions-called-once'
lv2wrap.cpp:5:17: error: expected namespace name
using namespace calfplugins;
```
This PR fixes that problem.

Fix compiling without USE_LV2

---

src/connector.cpp

Fixes out of bounds access that will happen if "connect" is clicked on an calfjackhost plugin and currently no connection is active

Fix out of bounds access when using calfjackhost without an existing

---

src/analyzer.cpp
src/jack_client.cpp
src/modules_dist.cpp
src/modules_limit.cpp

I had some troubles to compile Calf because of some type/casting errors.
Fixed that by forcing the types.
(Was it a good idea ?)

Fix some type errors

---

src/metadata.cpp

Assign all the plugins the same unified creator metadata, so
applications like Ardour will show all Calf plugins in a single
creator category:
Mixer, New Plugin, By Creator, Calf Studio Gear, ...

Unified creator metadata

---

src/makerdf.cpp

We have to use label from ladspa_plugin_info (e.g 'Filter') instead of name
set in presets.xml (e.g 'filter').
Fixes:
| Error opening file /usr/lib/lv2/calf.lv2/presets-filter.ttl (No such file or directory)
| lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/calf.lv2/presets-filter.ttl'
| Error opening file /usr/lib/lv2/calf.lv2/presets-filter.ttl (No such file or directory)
| lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/calf.lv2/presets-filter.ttl'
| Error opening file /usr/lib/lv2/calf.lv2/presets-filter.ttl (No such file or directory)
| lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/calf.lv2/presets-filter.ttl'
| Error opening file /usr/lib/lv2/calf.lv2/presets-flanger.ttl (No such file or directory)
...
After …

makerdf: fix preset file name in manifest

---

src/gtk_main_win.cpp

Hi there,
this bunch of commits is a minor change in calf so that primitive window managers (such as fluxbox where I had this problem, fixed and tested it) can separate across CALF instances. This way they can remember individual window positions and perhaps workspaces as well should that be required by the user. 
Unlike what is suggested by https://developer.gnome.org/gtk2/stable/GtkWindow.html#gtk-window-set-wmclass , the gtk_window_set_role () does not seem to be interpreted correctly by fluxbox window manager, which uses the X_hints fields "class" and "name" to separate across instances.

small update to make fluxbox able to separate calf instances

---

src/calf/giface.h
src/giface.cpp
src/metadata.cpp

The unit in this case is dBFS (absolute digital volume) not dB (analog/realtive volume).
Introduce a PF_UNIT_DBFS unit constant and use it in metadata.

Clarify the units for line-graphs and dynamics thresholds:

---

src/calf/jackhost.h
src/ctl_knob.cpp

HI,
Recent hardening of build flags in Fedora uncovered a bug in calf that causes crash at two different places.
https://bugzilla.redhat.com/show_bug.cgi?id=1581433
We got user verification that the suggested commits fix the crash problem.

crash fix: vector index

---

src/audio_fx.cpp
src/modules_limit.cpp

#188 
This fixes the crash in Limiter.
It considers that parameters may not be connected at the time of `set_sample_rate`.
If my understanding is correct, the null check is sufficient.
It will delay the update until later, in the chain of calls `activate` → `params_changed`.

fix a segfault in limiter and a build error

---

src/calf/lv2wrap.h
src/modules_filter.cpp

Fixing a few problems I discover as I run calf plugins in valgrind and my [testing host](https://github.com/jpcima/lv2-plugin-checker).
* uninitialized members
* wrapper which is leaked when library unloads. I don't think it's a problem to have it stored in static segment instead.

Fix memory problems

---

configure.ac
src/calf/lv2_options.h
src/calf/lv2_ui.h
src/calf/lv2wrap.h
src/makerdf.cpp

In [1] lv2-core.pc was removed and location of header files was reworked. This series prepares for next release of LV2.
Changes were build tested with LV2 1.14.0 and latest git
[1] https://github.com/drobilla/lv2/commit/4db67120efca2d4c200d2e1ba5cf3d7b97cab97e

Detect and builf properly for upcoming LV2

---

src/analyzer.cpp
src/audio_fx.cpp
src/calf/fixed_point.h
src/calf/giface.h
src/calf/osctl.h
src/calf/primitives.h
src/calf/utils.h
src/giface.cpp
src/modules_comp.cpp
src/modules_delay.cpp
src/modules_dist.cpp
src/modules_filter.cpp
src/modules_limit.cpp
src/modules_mod.cpp
src/modules_tools.cpp
src/organ.cpp
src/utils.cpp

I've made some changes to allow it to compile in visual studio. I'm currently using it for lmms so not everything has been ported. I've split up the issues in several commits so it's easier to pick and choose if necessary.

msvc compatibility

---

.gitignore
src/host_session.cpp
src/jackhost.cpp

I moved the window creation out of the constructor of host_session and init_gui to a place where command line parameters are parsed, so that the default value of true is not used at this point.
(#184 )

fix headless mode (#184)

---

src/host_session.cpp
src/jackhost.cpp

`host_session` handles signals and sets up stopping gui_loop on next idle_call after which the main application terminates.
In --no-gui mode `host_session::on_idle()` is never called and the main application doesn't notice that a termination is requested.
So instead of a while(1)-loop,` quit_on_next_idle_call` is inquired to determine termination.
(#184)

fix event handlers when using no-gui (#184)

---

src/host_session.cpp

deallocation of main_win memory should not happen in host_session's deconstructor because its allocation happens in host_session::open() which may not be called (eg. on --version or --help flag).
This moves the deallocation to host_session::close() and should fix issue #232.

fix segmentation fault [issue #232]

---

src/calf/modules_dev.h

Fix the bug reported by the issue #77.

make pitch bend of Fluidsynth LV2 usable for all channels

---

src/Makefile.am

When building calf with slibtool (https://dev.midipix.org/cross/slibtool) the build fails.
```
rdlibtool --tag=CXX --mode=link g++ -ffast-math -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -g -O2 -O3 -finline-functions -finline-functions-called-once -finline-limit=80 -Wall -o calfbenchmark benchmark.o calf.la
rdlibtool: lconf: {.name="libtool"}. …
```

Build fixes for slibtool

---

src/giface.cpp

With `-Werror` with GCC 9:
```
error: catching polymorphic type 'struct calf_utils::file_exception' by value [-Werror=catch-value=]
```

calf_plugins::load_gui_xml: Fix catching exception by value

---

src/Makefile.am

LLVM's LLD handles the -retain-symbols-file option (used by -export-symbols-regex in libtool) differently from GNU ld, causing undefined references during link. This commit removes the -export-symbols-regex option from libcalf_la_LDFLAGS since by default libtool exports all symbols anyway, so it should not be necessary.
Fixes https://github.com/calf-studio-gear/calf/issues/156.

Fix build with LLD

---

src/gui.cpp

- first check if ~/.calfrc exists, if it does use it
- otherwise attempt to create $XDG_CONFIG_HOME/calf/ if it does not exist
- if the folder now exists use as path $XDG_CONFIG_HOME/calf/calfrc, otherwise fall back to ~/.calfrc

allow placing calfrc under $XDG_CONFIG_HOME

---

src/modules_dist.cpp

In response to the debug message `fluidsynth: error: requested set value for setting 'synth.midi-channels' out of range`. FluidSynth sets a minimum of 16 midi channels internally. In this case you set it to 7 (_synths) explicitly and get the minimum 16 back accompanied by a message. http://www.fluidsynth.org/api/fluidsettings.xml#synth.midi-channels

FluidSynth minimum number of midi channels is 16

---

src/Makefile.am

Fixes loading of lv2 plugin and its gui.

build: fix symlinks in lv2dir

---

src/modules_limit.cpp

Hi from the LMMS team. I'm working on adding LADSPA support to MSVC. Someone had attempted to add ladspa support around a year ago and have upstreamed some changes. They fixed all compile time issues but they left out one runtime issue, ie the limiter crashes on the MSVC build of LMMS. 
The fix : 
`STACKALLOC` uses VLAs on other platforms and `_alloca()` on MSVC, because MSVC doesn't support VLAs. But the problem with using `_alloca()` inside the loop is that it leads to buffer overflow, so I moved it out of the loop. Looks like a rather harmless change and doesn't seem to cause any issues so far, though further testing is appreciated.

Fix runtime memory leaks on MSVC

---

src/calf/modules_filter.h
src/modules_comp.cpp
src/modules_delay.cpp
src/modules_dist.cpp
src/modules_tools.cpp

This should fix the following plugins in LMMS (and still work in other DAWs):
```
Compensation Delay Line
Saturator
Exciter
Bass Enhancer
Crusher
Stereo Tools
Multi Spread
Analyzer
Transient Designer
Tape Simulator
```
Note, I started LMMS like this:
```bash
LMMS_IGNORE_BLACKLIST=1 LV2_PATH=/path/to/calf/installation/of/this/pr/lib/lv2/ install/bin/lmms
```
What I did test:
* LMMS: Each effect does not crash when playing a note with default settings
What I did not test:
* Does it work in LMMS with non-default settings? Especially, changing options of the "Stereo Tools" might be interesting, because #278 is about issues with mono vs stereo.
* Does it still work in other DAWs?

Fixes #278: Do not read/write unconnected ports

---

configure.ac
src/Makefile.am

The Mac OS linker does not support `-z,nodelete` so I added an check for that and omitted this flag to make calf compile on OS X.

Test if linker supports nodelete

---

src/Makefile.am

Feel free to review, but I will merge this in the next 24 hours.
Source: https://cgit.freebsd.org/ports/tree/audio/calf-lv2/files/patch-src_Makefile.am
References #306

Automake: Remove use of the -module parameter

---

cmake/FindFluidSynth.cmake

This PR should fix the broken MSVC CI.
It was broken because on Windows, the FluidSynth library is named "fluidsynth-3" rather than just "fluidsynth". I think this is because the Linux version uses ".so.3" so they did it that way as the Windows equivalent.
NOTE: Since you cache the vcpkg builds, this problem might not be visible until you delete the cache or otherwise are forced to rebuild the vcpkg packages. I fixed this exact same problem in LMMS/lmms. See: https://github.com/LMMS/lmms/pull/7702

Fix FluidSynth detection on Windows when using vcpkg

---

src/utils.cpp

No functional changes here, but allows building veal regardless of whether the `UNICODE` macro is defined

MSVC: Always use Win32 ANSI functions

---

src/CMakeLists.txt

In 0663a6ee6f4a455d4e483fe77cae951aee9a1a16, DESTDIR was added to both the name of the symlink and its destination. The latter isn't correct - it needs to point to the final location of the file once it's installed, not the temporary DESTDIR directory.
(This makes the behaviour match what the autoconf build system used to do.)

CMake: Remove DESTDIR from symlink destinations

---

src/CMakeLists.txt

Windows requires developer mode switched on to create symlinks, so this makes symlinks impractical on Windows. Thanks to @tresf for the hint.

Windows: Copy libs, no symlinks

---

.gitignore
.svnignore
CMakeLists.txt
calf.desktop
configure.ac.deprecated

The `Version` must be the "Version of the Desktop Entry Specification", and not of the application.
This also updates/fixes the `Categories` section.
Fixes https://955628.bugs.gentoo.org/attachment.cgi?id=928147 .

Fix calf.desktop
